[manifest]
version = "1.2"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = """       elseif _c.name == "The World" then loc_vars = {cfg.max_highlighted, localize(cfg.suit_conv, 'suits_plural'), colours = {G.C.SUITS[cfg.suit_conv]}}
       end
       localize{type = 'descriptions', key = _c.key, set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}"""
position = "after"
payload = """    
elseif _c.set == 'AikoyoriExtraBases' then
    local x_loc_vars = _c.vars or loc_vars
    if card and card.is_null and (card.ability.set == "Enhanced" or card.ability.set == "Default") then
        local gend = false
        local last_letter = string.lower(string.sub(x_loc_vars[1], -1))
        local xkey = nil
        if(AKYRS.non_letter_symbols_reverse[last_letter]) then
            xkey = "symbols"
        end
        if(tonumber(last_letter)) then
            xkey = "numbers"
        end
        if not key then
            if (G.GAME.akyrs_letters_mult_enabled) then
                localize{type = 'descriptions', key = "lettersMult", set = _c.set, vars = _c.vars or loc_vars}
                gend = true
            end
            if (G.GAME.akyrs_letters_xmult_enabled) then
                localize{type = 'descriptions', key = "lettersXMult", set = _c.set, vars = _c.vars or loc_vars}
                gend = true
            end
        end
        if((_c.vars or loc_vars)[4]) then
            localize{type = 'descriptions', key = "letterCardFrequency", set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
        end
        if not gend then
            full_UI_table.name = localize{type = 'name', set = _c.set, nodes = full_UI_table.name,  key = xkey or "letters", vars = _c.vars or loc_vars}
        end
        localize{type = 'other', key = 'null_card', nodes = desc_nodes, vars = _c.vars or loc_vars}
    else
        if x_loc_vars[1] and string.sub(x_loc_vars[1], -1) then
            local last_letter = string.lower(string.sub(x_loc_vars[1], -1))
            local key = "letters"
            if(AKYRS.non_letter_symbols_reverse[last_letter]) then
                key = "symbols"
            end
            if(tonumber(last_letter)) then
                key = "numbers"
            end
            localize{type = 'descriptions', key = key , set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
        else 
            localize{type = 'descriptions', key = "null_card", set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
        end
        
        if(G.GAME.akyrs_letters_mult_enabled or G.GAME.akyrs_letters_xmult_enabled) then
            if(G.GAME.akyrs_letters_mult_enabled) then
                localize{type = 'descriptions', key = "lettersMult", set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
            end
            
            if(G.GAME.akyrs_letters_xmult_enabled) then
                localize{type = 'descriptions', key = "lettersXMult", set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
            end
        end
        if((_c.vars or loc_vars)[4]) then
            localize{type = 'descriptions', key = "letterCardFrequency", set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
        end
    end
elseif _c.set == 'DescriptionDummy' then
    localize{type = 'descriptions', key = _c.key, set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
elseif _c.set == 'FakeCenter' then
    localize{type = 'descriptions', key = _c.key, set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
elseif _c.set == 'Judgement' then
    localize{type = 'descriptions', key = _c.key, set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
"""
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = """    if not hide_desc and card and card.ability and (card.ability.extra_slots_used or 0) ~= 0 then"""
position = "before"
payload = """
if card then
    if card.akyrs_judgement and (AKYRS.is_life_enabled() or card.akyrs_collection_judgement) then
        local akyrs_judgement = AKYRS.Judgements[card.akyrs_judgement]
        if akyrs_judgement then
            local t = { key = card.akyrs_judgement..("_"..AKYRS.get_life_mode()), set = 'Judgement' }
            if card.akyrs_collection_judgement then
                t = { key = card.akyrs_judgement.."_none", set = 'Judgement' }
            end
            local res = {}
            if akyrs_judgement.loc_vars and type(akyrs_judgement.loc_vars) == 'function' then
                res = akyrs_judgement:loc_vars(info_queue, card) or {}
                t.vars = res.vars or {}
                t.key = res.key or t.key
                t.set = res.set or t.set
            end
            info_queue[#info_queue+1] = t
        end
    end
end
"""
overwrite = true
match_indent = true


[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = """  for g_k, group in pairs(G.localization) do"""
position = "before"
payload = """
G.localization.akyrs_misc_parsed = {}
for k, v in pairs(G.localization.misc.akyrs_misc or {}) do
    G.localization.akyrs_misc_parsed[k] = {}
    for kk, vv in ipairs(v) do
        G.localization.akyrs_misc_parsed[k][kk] = {multi_line = true}
        for kkk, vvv in ipairs(vv) do
            G.localization.akyrs_misc_parsed[k][kk][kkk] = loc_parse_string(vvv)
        end
    end
end"""
overwrite = true
match_indent = true


[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = """  elseif args.type == 'raw_descriptions' then """
position = "before"
payload = """elseif args.type == 'akyrs_misc' then 
    loc_target = {multi_line = true}
    loc_target.text_parsed = G.localization.akyrs_misc_parsed[args.key][args.index]"""
overwrite = true
match_indent = true


[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = """            spacing = _spacing,"""
position = "after"
payload = """shadow = args.akyrs_dynatext_shadow,
y_offset = args.akyrs_y_offset,
"""
overwrite = true
match_indent = true



[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = """        elseif part.control.E then"""
position = "at"
payload = """elseif part.control.E or args.akyrs_default_dynatext_effect then"""
overwrite = true
match_indent = true



[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = """          local text_effects"""
position = "after"
payload = """if args.akyrs_default_dynatext_effect then
    part.control.E = args.akyrs_default_dynatext_effect
end"""
overwrite = true
match_indent = true


[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = """            object = DynaText({string = {assembled_string}, colours = {part.control.V and args.vars.colours[tonumber(part.control.V)] or loc_colour(part.control.C or nil)},"""
position = "at"
payload = """object = DynaText({string = {assembled_string}, colours = {part.control.V and args.vars.colours[tonumber(part.control.V)] or loc_colour(part.control.C or nil, args.text_colour)},"""
overwrite = true
match_indent = true



[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = """            _float = true; _silent = true; _pop_in = 0"""
position = "after"
payload = """if args.akyrs_force_no_popin then _pop_in = nil end"""
overwrite = true
match_indent = true


[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = """            _float = true; _silent = true; _pop_in = 0"""
position = "after"
payload = """if args.akyrs_force_no_popin then _pop_in = nil end"""
overwrite = true
match_indent = true



[[patches]]
[patches.pattern]
target = "card.lua"
pattern = """    if self.config.center.unlocked == false and not self.bypass_lock then --For everyting that is locked"""
position = "before"
payload = """    if not self.bypass_lock and self.config.center.unlocked ~= false and
((((self or {}).config or {}).center or {}).akyrs_undiscover_tooltip) and
not self.config.center.discovered and 
((self.area ~= G.jokers and self.area ~= G.consumeables and self.area) or not self.area) then
    card_type = 'Undiscovered'
end"""
overwrite = true
match_indent = true



[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = """				self.children.center = SMODS.create_sprite(self.T.x, self.T.y, self.T.w, self.T.h, "Voucher", G.v_locked.pos)"""
position = "after"
payload = """elseif self.config.center.akyrs_locked_sprites and not self.config.center.unlocked and not self.params.bypass_discovery_center then
    local spr = self.config.center.akyrs_locked_sprites
    self.children.center = SMODS.create_sprite(self.T.x, self.T.y, self.T.w, self.T.h, spr.atlas, spr.pos)
elseif self.config.center.akyrs_undiscovered_sprites and self.config.center.unlocked and not self.config.center.discovered and not self.params.bypass_discovery_center then
    local spr = self.config.center.akyrs_undiscovered_sprites
    self.children.center = SMODS.create_sprite(self.T.x, self.T.y, self.T.w, self.T.h, spr.atlas, spr.pos)"""
overwrite = true
match_indent = true

