[manifest]
version = "1.2"
dump_lua = true
priority = 0


[[patches]]
[patches.pattern]
target = """=[SMODS _ "src/overrides.lua"]"""
pattern = """		total_weight = total_weight + (v.weight) -- total all the weights of the polled editions"""
position = "before"
payload = """if v and v.weight then"""
overwrite = true
match_indent = true




[[patches]]
[patches.pattern]
target = """=[SMODS _ "src/overrides.lua"]"""
pattern = """		total_weight = total_weight + (v.weight) -- total all the weights of the polled editions"""
position = "after"
payload = """end"""
overwrite = true
match_indent = true




[[patches]]
[patches.pattern]
target = """game.lua"""
pattern = """    self:save_progress()"""
position = "before"
payload = """akyrs_init_prototypes(self)"""
overwrite = true
match_indent = true



[[patches]]
[patches.pattern]
target = """functions/common_events.lua"""
pattern = """        --create the pool"""
position = "before"
payload = """if G.GAME.akyrs_ban_everything and not _type then _type = 'Joker' end"""
overwrite = true
match_indent = true



[[patches]]
[patches.copy]
target = """game.lua"""
position = "prepend"
sources = [
    "modules/hooks/prepend_to_game.lua",
]

