[manifest]
version = "1.2"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/card_draw.lua"]'''
pattern = """            self.children.back:draw(overlay)"""
position = "before"
payload = '''
if not AKYRS.back_render_override(self, self.children.back, overlay) then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/card_draw.lua"]'''
pattern = """            self.children.back:draw(overlay)"""
position = "after"
payload = '''
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/card_draw.lua"]'''
pattern = """            self.children.back:draw_shader('dissolve')"""
position = "before"
payload = '''
if not AKYRS.back_render_override(self, self.children.back) then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/card_draw.lua"]'''
pattern = """            self.children.center:draw_shader('dissolve')"""
position = "before"
payload = '''
if self.config.center.akyrs_shader_overlay then
    self.children.center:draw_shader(self.config.center.akyrs_shader_overlay, nil, self.ARGS.send_to_shader)
else
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/card_draw.lua"]'''
pattern = """            self.children.center:draw_shader('dissolve')"""
position = "after"
payload = '''
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/card_draw.lua"]'''
pattern = """            self.children.back:draw_shader('dissolve')"""
position = "after"
payload = '''
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = """        if G.GAME.blind then t[#t + 1] = { object = G.GAME.blind, scored_card = G.GAME.blind.children.animatedSprite } end"""
position = "before"
payload = '''
if G.GAME.blind then G.GAME.blind.children = G.GAME.blind.children or {} end
'''
match_indent = true


[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/card_draw.lua"]'''
pattern = """    if not self.states.visible then return end"""
position = "after"
payload = '''
AKYRS.rotate_cards(self)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/card_draw.lua"]'''
pattern = """        if SMODS.DrawSteps[k]:check_conditions(self, layer) then SMODS.DrawSteps[k].func(self, layer) end
    end"""
position = "after"
payload = '''
AKYRS.post_rotate_cards(self)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''tag.lua'''
pattern = """    if not for_collection then self:set_ability() end"""
position = "after"
payload = '''if for_collection then self.akyrs_enabled = true end
self.akyrs_is_collection = for_collection'''
match_indent = true
